import { HeritageType } from "@/models/types/inAppCreations/heritage";

export const countries = [
    { name: "Andorra", flagCode: "AD" },
    { name: "United Arab Emirates", flagCode: "AE" },
    { name: "Antigua and Barbuda", flagCode: "AG" },
    { name: "Anguilla", flagCode: "AI" },
    { name: "Albania", flagCode: "AL" },
    { name: "Armenia", flagCode: "AM" },
    { name: "Angola", flagCode: "AO" },
    { name: "Antarctica", flagCode: "AQ" },
    { name: "Argentina", flagCode: "AR" },
    { name: "American Samoa", flagCode: "AS" },
    { name: "Austria", flagCode: "AT" },
    { name: "Australia", flagCode: "AU" },
    { name: "Aruba", flagCode: "AW" },
    { name: "Åland Islands", flagCode: "AX" },
    { name: "Azerbaijan", flagCode: "AZ" },
    { name: "Bosnia and Herzegovina", flagCode: "BA" },
    { name: "Barbados", flagCode: "BB" },
    { name: "Bangladesh", flagCode: "BD" },
    { name: "Belgium", flagCode: "BE" },
    { name: "Burkina Faso", flagCode: "BF" },
    { name: "Bulgaria", flagCode: "BG" },
    { name: "Bahrain", flagCode: "BH" },
    { name: "Burundi", flagCode: "BI" },
    { name: "Benin", flagCode: "BJ" },
    { name: "Saint Barthélemy", flagCode: "BL" },
    { name: "Bermuda", flagCode: "BM" },
    { name: "Brunei", flagCode: "BN" },
    { name: "Bolivia", flagCode: "BO" },
    { name: "Brazil", flagCode: "BR" },
    { name: "Bahamas", flagCode: "BS" },
    { name: "Bhutan", flagCode: "BT" },
    { name: "Botswana", flagCode: "BW" },
    { name: "Belarus", flagCode: "BY" },
    { name: "Belize", flagCode: "BZ" },
    { name: "Canada", flagCode: "CA" },
    { name: "Cocos Islands", flagCode: "CC" },
    { name: "Democratic Republic of Congo", flagCode: "CD" },
    { name: "Central African Republic", flagCode: "CF" },
    { name: "Congo", flagCode: "CG" },
    { name: "Switzerland", flagCode: "CH" },
    { name: "Côte d'Ivoire", flagCode: "CI" },
    { name: "Cook Island", flagCode: "CK" },
    { name: "Chile", flagCode: "CL" },
    { name: "Cameroon", flagCode: "CM" },
    { name: "China", flagCode: "CN" },
    { name: "Colombia", flagCode: "CO" },
    { name: "Costa Rica", flagCode: "CR" },
    { name: "Cuba", flagCode: "CU" },
    { name: "Cape Verde", flagCode: "CV" },
    { name: "Curaçao", flagCode: "CW" },
    { name: "Christmas Island", flagCode: "CX" },
    { name: "Cyprus", flagCode: "CY" },
    { name: "Czech Republic", flagCode: "CZ" },
    { name: "Germany", flagCode: "DE" },
    { name: "Djibouti", flagCode: "DJ" },
    { name: "Denmark", flagCode: "DK" },
    { name: "Dominica", flagCode: "DM" },
    { name: "Dominican Republic", flagCode: "DO" },
    { name: "Ecuador", flagCode: "EC" },
    { name: "Estonia", flagCode: "EE" },
    { name: "Egypt", flagCode: "EG" },
    { name: "Western Sahara", flagCode: "EH" },
    { name: "Eritrea", flagCode: "ER" },
    { name: "Spain", flagCode: "ES" },
    { name: "Ethiopia", flagCode: "ET" },
    { name: "Finland", flagCode: "FI" },
    { name: "Fiji", flagCode: "FJ" },
    { name: "Falkland Islands", flagCode: "FK" },
    { name: "Micronesia (Federated States of)", flagCode: "FM" },
    { name: "Faroe Island", flagCode: "FO" },
    { name: "France", flagCode: "FR" },
    { name: "Gabon", flagCode: "GA" },
    { name: "England", flagCode: "GB-ENG" },
    { name: "Scotland", flagCode: "GB-SCT" },
    { name: "United Kingdom", flagCode: "GB-UKM" },
    { name: "Wales", flagCode: "GB-WLS" },
    { name: "Northern Ireland", flagCode: "GB-NIR" },
    { name: "Grenada", flagCode: "GD" },
    { name: "Georgia", flagCode: "GE" },
    { name: "French Guiana", flagCode: "GF" },
    { name: "Guernsey", flagCode: "GG" },
    { name: "Ghana", flagCode: "GH" },
    { name: "Gibraltar", flagCode: "GI" },
    { name: "Greenland", flagCode: "GL" },
    { name: "Gambia", flagCode: "GM" },
    { name: "Guinea", flagCode: "GN" },
    { name: "Guadeloupe", flagCode: "GP" },
    { name: "Equatorial Guinea", flagCode: "GQ" },
    { name: "Greece", flagCode: "GR" },
    { name: "South Georgia and the South Sandwich Islands", flagCode: "GS" },
    { name: "Guatemala", flagCode: "GT" },
    { name: "Guam", flagCode: "GU" },
    { name: "Guinea-Bissau", flagCode: "GW" },
    { name: "Guyana", flagCode: "GY" },
    { name: "Hong Kong", flagCode: "HK" },
    { name: "Heard Island and McDonald Islands", flagCode: "HM" },
    { name: "Honduras", flagCode: "HN" },
    { name: "Croatia", flagCode: "HR" },
    { name: "Haiti", flagCode: "HT" },
    { name: "Hungary", flagCode: "HU" },
    { name: "Indonesia", flagCode: "ID" },
    { name: "Ireland", flagCode: "IE" },
    { name: "Israel", flagCode: "IL" },
    { name: "Isle of Man", flagCode: "IM" },
    { name: "India", flagCode: "IN" },
    { name: "British Indian Ocean Territory", flagCode: "IO" },
    { name: "Iraq", flagCode: "IQ" },
    { name: "Iran", flagCode: "IR" },
    { name: "Iceland", flagCode: "IS" },
    { name: "Italy", flagCode: "IT" },
    { name: "Jersey", flagCode: "JE" },
    { name: "Jamaica", flagCode: "JM" },
    { name: "Jordan", flagCode: "JO" },
    { name: "Japan", flagCode: "JP" },
    { name: "Kenya", flagCode: "KE" },
    { name: "Kyrgyzstan", flagCode: "KG" },
    { name: "Cambodia", flagCode: "KH" },
    { name: "Kiribati", flagCode: "KI" },
    { name: "Comoros", flagCode: "KM" },
    { name: "Saint Kitts and Nevis", flagCode: "KN" },
    { name: "Korea (the Democratic People's Republic of)", flagCode: "KP" },
    { name: "Korea (the Republic of)", flagCode: "KR" },
    { name: "Kuwait", flagCode: "KW" },
    { name: "Cayman Islands", flagCode: "KY" },
    { name: "Kazakhstan", flagCode: "KZ" },
    { name: "Lao People's Democratic Republic", flagCode: "LA" },
    { name: "Lebanon", flagCode: "LB" },
    { name: "Saint Lucia", flagCode: "LC" },
    { name: "Liechtenstein", flagCode: "LI" },
    { name: "Sri Lanka", flagCode: "LK" },
    { name: "Liberia", flagCode: "LR" },
    { name: "Lesotho", flagCode: "LS" },
    { name: "Lithuania", flagCode: "LT" },
    { name: "Luxembourg", flagCode: "LU" },
    { name: "Latvia", flagCode: "LV" },
    { name: "Libya", flagCode: "LY" },
    { name: "Morocco", flagCode: "MA" },
    { name: "Monaco", flagCode: "MC" },
    { name: "Moldova", flagCode: "MD" },
    { name: "Montenegro", flagCode: "ME" },
    { name: "Saint Martin", flagCode: "MF" },
    { name: "Madagascar", flagCode: "MG" },
    { name: "Marshall Islands", flagCode: "MH" },
    { name: "North Macedonia", flagCode: "MK" },
    { name: "Mali", flagCode: "ML" },
    { name: "Myanmar", flagCode: "MM" },
    { name: "Mongolia", flagCode: "MN" },
    { name: "Macao", flagCode: "MO" },
    { name: "Northern Mariana Islands", flagCode: "MP" },
    { name: "Martinique", flagCode: "MQ" },
    { name: "Mauritania", flagCode: "MR" },
    { name: "Montserrat", flagCode: "MS" },
    { name: "Malta", flagCode: "MT" },
    { name: "Mauritius", flagCode: "MU" },
    { name: "Maldives", flagCode: "MV" },
    { name: "Malawi", flagCode: "MW" },
    { name: "Mexico", flagCode: "MX" },
    { name: "Malaysia", flagCode: "MY" },
    { name: "Mozambique", flagCode: "MZ" },
    { name: "Namibia", flagCode: "NA" },
    { name: "New Caledonia", flagCode: "NC" },
    { name: "Niger", flagCode: "NE" },
    { name: "Norfolk Island", flagCode: "NF" },
    { name: "Nigeria", flagCode: "NG" },
    { name: "Nicaragua", flagCode: "NI" },
    { name: "Netherlands", flagCode: "NL" },
    { name: "Norway", flagCode: "NO" },
    { name: "Nepal", flagCode: "NP" },
    { name: "Nauru", flagCode: "NR" },
    { name: "Niue", flagCode: "NU" },
    { name: "New Zealand", flagCode: "NZ" },
    { name: "Oman", flagCode: "OM" },
    { name: "Panama", flagCode: "PA" },
    { name: "Peru", flagCode: "PE" },
    { name: "French Polynesia", flagCode: "PF" },
    { name: "Papua New Guinea", flagCode: "PG" },
    { name: "Philippines", flagCode: "PH" },
    { name: "Pakistan", flagCode: "PK" },
    { name: "Poland", flagCode: "PL" },
    { name: "Saint Pierre and Miquelon", flagCode: "PM" },
    { name: "Pitcairn", flagCode: "PN" },
    { name: "Puerto Rico", flagCode: "PR" },
    { name: "Palestine", flagCode: "PS" },
    { name: "Portugal", flagCode: "PT" },
    { name: "Palau", flagCode: "PW" },
    { name: "Paraguay", flagCode: "PY" },
    { name: "Qatar", flagCode: "QA" },
    { name: "Réunion", flagCode: "RE" },
    { name: "Romania", flagCode: "RO" },
    { name: "Serbia", flagCode: "RS" },
    { name: "Russian Federation", flagCode: "RU" },
    { name: "Rwanda", flagCode: "RW" },
    { name: "Saudi Arabia", flagCode: "SA" },
    { name: "Solomon Islands", flagCode: "SB" },
    { name: "Seychelles", flagCode: "SC" },
    { name: "Sudan", flagCode: "SD" },
    { name: "Sweden", flagCode: "SE" },
    { name: "Singapore", flagCode: "SG" },
    { name: "Saint Helena, Ascension Island, Tristan da Cunha", flagCode: "SH" },
    { name: "Slovenia", flagCode: "SI" },
    { name: "Svalbard and Jan Mayen", flagCode: "SJ" },
    { name: "Slovakia", flagCode: "SK" },
    { name: "Sierra Leone", flagCode: "SL" },
    { name: "San Marino", flagCode: "SM" },
    { name: "Senegal", flagCode: "SN" },
    { name: "Somalia", flagCode: "SO" },
    { name: "Suriname", flagCode: "SR" },
    { name: "South Sudan", flagCode: "SS" },
    { name: "Sao Tome and Principe", flagCode: "ST" },
    { name: "El Salvador", flagCode: "SV" },
    { name: "Sint Maarten", flagCode: "SX" },
    { name: "Syrian Arab Republic", flagCode: "SY" },
    { name: "Eswatini", flagCode: "SZ" },
    { name: "Turks and Caicos Islands", flagCode: "TC" },
    { name: "Chad", flagCode: "TD" },
    { name: "French Southern Territories", flagCode: "TF" },
    { name: "Togo", flagCode: "TG" },
    { name: "Thailand", flagCode: "TH" },
    { name: "Tajikistan", flagCode: "TJ" },
    { name: "Tokelau", flagCode: "TK" },
    { name: "Timor-Leste", flagCode: "TL" },
    { name: "Turkmenistan", flagCode: "TM" },
    { name: "Tunisia", flagCode: "TN" },
    { name: "Tonga", flagCode: "TO" },
    { name: "Turkey", flagCode: "TR" },
    { name: "Trinidad and Tobago", flagCode: "TT" },
    { name: "Tuvalu", flagCode: "TV" },
    { name: "Taiwan", flagCode: "TW" },
    { name: "Tanzania, the United Republic of", flagCode: "TZ" },
    { name: "Ukraine", flagCode: "UA" },
    { name: "Uganda", flagCode: "UG" },
    { name: "United States Minor Outlying Islands", flagCode: "UM" },
    { name: "United States of America", flagCode: "US" },
    { name: "Uruguay", flagCode: "UY" },
    { name: "Uzbekistan", flagCode: "UZ" },
    { name: "Holy See", flagCode: "VA" },
    { name: "Saint Vincent and the Grenadines", flagCode: "VC" },
    { name: "Venezuela (Bolivarian Republic of)", flagCode: "VE" },
    { name: "Virgin Islands (British)", flagCode: "VG" },
    { name: "Virgin Islands (U.S.)", flagCode: "VI" },
    { name: "Vietnam", flagCode: "VN" },
    { name: "Vanuatu", flagCode: "VU" },
    { name: "Wallis and Futuna", flagCode: "WF" },
    { name: "Samoa", flagCode: "WS" },
    { name: "Yemen", flagCode: "YE" },
    { name: "South Africa", flagCode: "ZA" },
    { name: "Zambia", flagCode: "ZM" },
    { name: "Zimbabwe", flagCode: "ZW" },
    { name: "Afghanistan", flagCode: "AF" },
    { name: "Bouvet Island", flagCode: "BV" }
] as HeritageType[];